version: '2'
services:
  elasticsearch:
    image: yfshare/elasticsearch:6.2.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/elk/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
      - /root/elk/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options:ro
      - /data/elk/elasticsearch:/data/elasticsearch

  kibana:
    image: yfshare/kibana:6.2.2
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/elk/kibana/kibana.yml:/etc/kibana/kibana.yml:ro

  logstash:
    image: yfshare/logstash:6.2.2
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/elk/logstash/logstash.yml:/etc/logstash/logstash.yml:ro
      - /root/elk/logstash/jvm.options:/etc/logstash/jvm.options:ro
      - /root/elk/logstash/conf.d/:/etc/logstash/conf.d/:ro
      - /data/elk/logstash:/data/logstash
    links:
      - elasticsearch
      - kibana
