FROM yfshare/jdk:8u172
MAINTAINER  yfshare

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

COPY "apache-maven-3.5.3-bin.tar.gz" "/"
COPY "maven.sh" "/etc/profile.d/"
COPY "jenkins-2.130.war" "/opt"
COPY "docker-entrypoint.sh" "/"

USER root
RUN set -x \
    && yum -y install git \
    && tar -zxf "/apache-maven-3.5.3-bin.tar.gz" \
    && mv "/apache-maven-3.5.3" "/usr/local/maven" \
    && rm -rf "/apache-maven-3.5.3-bin.tar.gz" \
    && sed -i '/<\/settings>/i\<localRepository\>\/data\/maven\/repository\<\/localRepository\>' /usr/local/maven/conf/settings.xml \
    && mkdir -p "/data/maven/repositor" \
    && yum clean all 

VOLUME ["/root/.jenkins","/data/maven/repository"]

EXPOSE 8080 50000

ENTRYPOINT /docker-entrypoint.sh
