version: '3'
services:
  jenkins:
    image: yfshare/jenkins:2.128
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    hostname: jenkins.example.com
    extra_hosts:
      jenkins.example.com: 127.0.0.1
    volumes:
      - /data/docker_mount/jenkins_home:/var/jenkins_home
      - /data/docker_mount/maven_repository:/data/maven/repository
      - /etc/localtime:/etc/localtime:ro
    restart: always
[root@localhost ~]# cat build/Dockerfile 
FROM jenkins/jenkins:2.128
MAINTAINER  yfshare

COPY "apache-maven-3.5.3-bin.tar.gz" "/"
COPY "jenkins.sh" "/usr/local/bin/"
COPY "maven.sh" "/etc/profile.d/"

USER root
RUN set -x \
    && apt-get update \
    && apt-get install -y vim ntpdate net-tools\
    && tar -zxf "/apache-maven-3.5.3-bin.tar.gz" \
    && mv "/apache-maven-3.5.3" "/usr/local/maven" \
    && rm -rf "/apache-maven-3.5.3-bin.tar.gz" \
    && ln -s /usr/local/maven/bin/mvn /usr/local/bin/ \
    && sed -i '/<\/settings>/i\<localRepository\>\/data\/maven\/repository\<\/localRepository\>' /usr/local/maven/conf/se
ttings.xml \    && mkdir -p /data/maven/repository \
    && chown -R jenkins:jenkins /data/maven/repository \
    && chown -R jenkins:jenkins /var/jenkins_home \
    && chown -R jenkins:jenkins /usr/local/maven \
    && apt-get clean

VOLUME ["/var/jenkins_home","/data/maven/repository"]

EXPOSE 8080 50000

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
