FROM jenkins/jenkins:2.130
MAINTAINER  yfshare

COPY "apache-maven-3.5.3-bin.tar.gz" "/"
COPY "jenkins.sh" "/usr/local/bin/"
COPY "maven.sh" "/etc/profile.d/"

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  

USER root
RUN set -x \
    && apt-get update \
    && apt-get install -y vim ntpdate net-tools\
    && tar -zxf "/apache-maven-3.5.3-bin.tar.gz" \
    && mv "/apache-maven-3.5.3" "/usr/local/maven" \
    && rm -rf "/apache-maven-3.5.3-bin.tar.gz" \
    && ln -s /usr/local/maven/bin/mvn /usr/local/bin/ \
    && sed -i '/<\/settings>/i\<localRepository\>\/data\/maven\/repository\<\/localRepository\>' /usr/local/maven/conf/settings.xml \
    && mkdir -p /data/maven/repository \
    && chown -R jenkins:jenkins /data/maven/repository \
    && chown -R jenkins:jenkins /var/jenkins_home \
    && chown -R jenkins:jenkins /usr/local/maven \
    && apt-get clean

VOLUME ["/var/jenkins_home","/data/maven/repository","/usr/local/maven/conf"]

EXPOSE 8080 50000

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
